### ISSUE TITLE
Put website in repo headline

### ISSUE THREAD

**Issue by mLuby** [karol-f/ngMario#3]
Would make it easier to get to! [http://blnight.github.io/ngMario](http://blnight.github.io/ngMario) 

![screen shot 2014-10-13 at 20 14 53](https://cloud.githubusercontent.com/assets/2483420/4623519/8faad624-5350-11e4-8475-7fe64f4637c5.png)
![screen shot 2014-10-13 at 20 14 58](https://cloud.githubusercontent.com/assets/2483420/4623520/9101cf00-5350-11e4-9320-eec0c4d4dd8a.png)

**Comment by karol-f** [comment]
Done, thank you.
