### ISSUE TITLE
Error when trying to init app

### ISSUE THREAD

**Issue by LeonardoBerlatto** [karol-f/ngMario#5]
When I run grunt to initialize the app, this errors comes out.

![image](https://user-images.githubusercontent.com/36887738/50786154-dedf8e80-1299-11e9-8fed-3d8936b2ab8c.png)

**Comment by karol-f** [comment]
Hi, this project is no longer maintained. Probably you are using to new Node.js version - but this is guess.

**Comment by karol-f** [comment]
@Doctor-28 Try https://github.com/JoshuaKGoldberg/Old-Deleted-FullScreenMario/tree/77b493c9ce9fb015a88995658b11d95e28f1e68e - JS Mario I've baed this on.
